### ISSUE TITLE
Is there a way to hide scrollbar after a short pediod of time ?

### ISSUE THREAD

**Issue by thmarinho** [jonstuebe/tailwindcss-scrollbar#1]
Hi,
I am trying to make the scrollbar disappear after a period of time without being used. Is there a way to do it ?
The code below.
Thanks in advance.

```
    <div className="[...} overflow-y-auto overflow-x-hidden scrollbar-w-2 scrollbar-thumb-rounded-full scrollbar-thumb-gray-400 scrollbar-track-grayBlue">
...
    </div>
```

**Comment by jonstuebe** [comment]
Not that I know of. Once you style the scroll bars using this method I believe they will always be there.

**Comment by thmarinho** [comment]
Thanks !
